import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderNavbar from "@/components/sections/header-navbar";
import Footer from "@/components/sections/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full fixed z-50 top-0 flex justify-center py-4 bg-white">
          <HeaderNavbar />
        </div>
        {children}
        <footer className="w-full flex justify-center bg-[#EDEDED] py-12">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
